name: Build and Publish Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-ci-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ci-base
          tags: |
            type=raw,value=v1.0.0
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=CI Base Image
            org.opencontainers.image.description=Foundational CI/CD Docker image with security tools
            org.opencontainers.image.vendor=spenceryork

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/ci-base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max