name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**"
    #   - "docker/**"
    #   - ".github/**"

jobs:
  claude-review:
    # Only run on external contributions or when specifically requested
    if: |
      github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' ||
      github.event.pull_request.author_association == 'CONTRIBUTOR' ||
      contains(github.event.pull_request.body, '@claude-review')
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Claude Code OAuth token
        id: check-token
        run: |
          if [ -z "${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}" ]; then
            echo "claude_token_available=false" >> $GITHUB_OUTPUT
            echo "⚠️ CLAUDE_CODE_OAUTH_TOKEN not configured. Skipping Claude review."
          else
            echo "claude_token_available=true" >> $GITHUB_OUTPUT
            echo "✅ Claude Code OAuth token is configured."
          fi

      - name: Run Claude Code Review
        if: steps.check-token.outputs.claude_token_available == 'true'
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            Please review this pull request focusing on:
            
            🔍 **Code Quality**
            - Follow repository conventions from CLAUDE.md
            - Check for Docker best practices
            - Validate GitHub Actions workflow syntax
            
            🐛 **Potential Issues**
            - Security vulnerabilities
            - Performance bottlenecks
            - Configuration errors
            
            🧪 **Testing & CI**
            - Test coverage adequacy
            - CI/CD pipeline compatibility
            - Integration with existing workflows
            
            ✅ **Action Items**
            Use `gh pr comment` to provide constructive feedback.
            Focus on actionable suggestions and improvements.
          
          claude_args: '--allowed-tools "Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Read,Grep,Glob"'

      - name: Fallback Manual Review Trigger
        if: steps.check-token.outputs.claude_token_available == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `## 🤖 Claude Code Review Unavailable
              
              The automated Claude Code review is not configured for this repository.
              
              **To enable automated reviews:**
              1. Set up a Claude Code OAuth token in repository secrets
              2. Add \`CLAUDE_CODE_OAUTH_TOKEN\` to repository secrets
              3. Re-run this workflow
              
              **For manual review:**
              - Review Docker configurations in \`docker/\` directory
              - Validate GitHub Actions workflows in \`.github/workflows/\`
              - Check security considerations per \`.github/SECURITY.md\`
              - Follow conventions outlined in \`CLAUDE.md\`
              
              cc: @${context.payload.pull_request.user.login}`
            });

      - name: Set review status
        if: always()
        run: |
          if [ "${{ steps.check-token.outputs.claude_token_available }}" == "true" ]; then
            echo "::notice title=Claude Review::Automated code review completed"
          else
            echo "::warning title=Setup Required::Claude Code OAuth token not configured"
            echo "::notice title=Manual Review::Fallback comment posted to PR"
          fi